[2022-11-30 18:59:19,245][wandb.jupyter][ERROR] - Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
[2022-11-30 19:05:35,865][asyncio][ERROR] - Task was destroyed but it is pending!
task: <Task pending name='Task-1' coro=<Kernel.poll_control_queue() running at /profils_cerea/dumontj/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py:284> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f971c81fa60>()]> cb=[_chain_future.<locals>._call_set_state() at /cerea_raid/users/dumontj/usr/anaconda3/envs/tf-gpu/lib/python3.8/asyncio/futures.py:367]>
